### ISSUE TITLE
`test_contrib_adapter.TestNestedRelationships` creates invalid data, fails upstream CI

### ISSUE THREAD

**Issue by glennmatthews** [nautobot/nautobot-app-ssot#412]
### Environment
* Python version:  
* Nautobot version:  2.2.0
* nautobot-ssot version:  

### Expected Behavior

Tests to pass upstream CI

### Observed Behavior

```
======================================================================
ERROR: test_foreign_key_in_many_to_many_field (nautobot_ssot.tests.test_contrib_adapter.TestNestedRelationships)
Test that many to many fields can contain foreign keys.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/source/nautobot_ssot/tests/test_contrib_adapter.py", line 340, in test_foreign_key_in_many_to_many_field
    ipam_models.VLAN.objects.create(
  File "/usr/local/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 453, in create
    obj.save(force_insert=True, using=self.db)
  File "/usr/local/lib/python3.8/site-packages/nautobot/ipam/models.py", line 1411, in save
    self.location = self._location
  File "/usr/local/lib/python3.8/site-packages/nautobot/ipam/models.py", line 1427, in location
    self.locations.set([value])
  File "/usr/local/lib/python3.8/site-packages/django/db/models/fields/related_descriptors.py", line 1015, in set
    self.add(*new_objs, through_defaults=through_defaults)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/fields/related_descriptors.py", line 950, in add
    self._add_items(
  File "/usr/local/lib/python3.8/site-packages/django/db/models/fields/related_descriptors.py", line 1144, in _add_items
    signals.m2m_changed.send(
  File "/usr/local/lib/python3.8/site-packages/django/dispatch/dispatcher.py", line 180, in send
    return [
  File "/usr/local/lib/python3.8/site-packages/django/dispatch/dispatcher.py", line 181, in <listcomp>
    (receiver, receiver(signal=self, sender=sender, **named))
  File "/usr/local/lib/python3.8/site-packages/nautobot/ipam/signals.py", line 118, in assert_locations_content_types
    raise ValidationError(
django.core.exceptions.ValidationError: {'locations': ["VLANs may not associate to Locations of types ['Building']."]}

----------------------------------------------------------------------
```

Most likely this is fixable by simply adding a `location_type.content_types.add(ContentType.objects.get_for_model(VLAN))` to the test.

### Steps to Reproduce
1.
2.
3.

**Comment by Kircheneer** [comment]
Fixed in #413
