### ISSUE TITLE
CI Failing on Wrong BIG-IP Netmiko Platform

### ISSUE THREAD

**Issue by jdrew82** [nautobot/nautobot-app-ssot#455]
### Environment
* Python version:  3.11
* Nautobot version:  2.2.3
* nautobot-ssot version:  2.6.1

### Expected Behavior
CI to pass for test_get_netmiko_platform_5_bigip unit test.

### Observed Behavior
Test fails with AssertionError:

```
======================================================================
FAIL: test_get_netmiko_platform_5_bigip (nautobot_ssot.tests.device42.unit.test_utils_device42.TestUtilsDevice42.test_get_netmiko_platform_5_bigip)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/parameterized/parameterized.py", line 533, in standalone_func
    return func(*(a + p.args), **p.kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/source/nautobot_ssot/tests/device42/unit/test_utils_device42.py", line 174, in test_get_netmiko_platform
    self.assertEqual(device42.get_netmiko_platform(sent), received)
AssertionError: 'bigip_f5' != 'f5_tmsh'
- bigip_f5
+ f5_tmsh
```

### Steps to Reproduce
1. Build dev environment for SSoT.
2. Run `invoke tests`.
3. Look at results.

**Comment by jdrew82** [comment]
I believe this is related to a change in the PYATS_LIB_MAPPER mapping in netutils.
