### ISSUE TITLE
Possible gRPC issue with Arista SSoT

### ISSUE THREAD

**Issue by qduk** [nautobot/nautobot-app-ssot#467]
### Environment
* Python version:  Unsure
* Nautobot version:  2.1.9
* nautobot-ssot version:  2.5.0

### Expected Behavior
Running the Arista SSoT successfully populates data into Nautobot.

### Observed Behavior
A gRPC error is raised during the sync. 

### Steps to Reproduce
1. Install SSoT app with Arista Integration
2. Run sync job

**Comment by qduk** [comment]
Traceback: 
```
[2024-05-09 23:53:26,378: WARNING/ForkPoolWorker-30] Exception ignored in:
[2024-05-09 23:53:26,382: WARNING/ForkPoolWorker-30] <function _Rendezvous.__del__ at 0x7fdf5d99e480>
[2024-05-09 23:53:26,386: WARNING/ForkPoolWorker-30] Traceback (most recent call last):
[2024-05-09 23:53:26,388: WARNING/ForkPoolWorker-30]   File "/usr/local/lib/python3.11/site-packages/grpc/_channel.py", line 561, in __del__
[2024-05-09 23:53:26,394: WARNING/ForkPoolWorker-30] with self._state.condition:
[2[2024-05-09 23:53:26,445: WARNING/ForkPoolWorker-30] AttributeError
[2024-05-09 23:53:26,447: WARNING/ForkPoolWorker-30] :
[2024-05-09 23:53:26,450: WARNING/ForkPoolWorker-30] '_MultiThreadedRendezvous' object has no attribute '_state'
[2024-05-09 23:53:26,452: WARNING/ForkPoolWorker-30] Exception ignored in:
[2024-05-09 23:53:26,454: WARNING/ForkPoolWorker-30] <function _Rendezvous.__del__ at 0x7fdf5d99e480>
[2024-05-09 23:53:26,457: WARNING/ForkPoolWorker-30] Traceback (most recent call last):
[2024-05-09 23:53:26,459: WARNING/ForkPoolWorker-30]   File "/usr/local/lib/python3.11/site-packages/grpc/_channel.py", line 561, in __del__
[2024-05-09 23:53:26,463: WARNING/ForkPoolWorker-30]
[2024-05-09 23:53:26,465: WARNING/ForkPoolWorker-30] with self._state.condition:
[2024-05-09 23:53:26,516: WARNING/ForkPoolWorker-30] AttributeError
[2024-05-09 23:53:26,518: WARNING/ForkPoolWorker-30] :
[2024-05-09 23:53:26,521: WARNING/ForkPoolWorker-30] '_Rendezvous' object has no attribute '_state'
[2024-05-09 23:53:26,544: ERROR/ForkPoolWorker-30] Task nautobot.extras.jobs.run_job[a2a6ea55-fc2f-440e-89c1-8c82761c563b] raised unexpected: RpcError()
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/celery/app/trace.py", line 477, in trace_task
    R = retval = fun(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/celery/app/trace.py", line 760, in __protected_call__
    return self.run(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/nautobot/extras/jobs.py", line 1136, in run_job
    result = job(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/nautobot/extras/jobs.py", line 149, in __call__
    return self.run(*args, **deserialized_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/source/nautobot_ssot/integrations/aristacv/jobs.py", line 140, in run
    super().run(dryrun=self.dryrun, memory_profiling=self.memory_profiling, *args, **kwargs)
  File "/source/nautobot_ssot/jobs/base.py", line 317, in run
    self.sync_data(memory_profiling)
  File "/source/nautobot_ssot/jobs/base.py", line 136, in sync_data
    self.load_source_adapter()
  File "/source/nautobot_ssot/integrations/aristacv/jobs.py", line 119, in load_source_adapter
    self.source_adapter.load()
  File "/source/nautobot_ssot/integrations/aristacv/diffsync/adapters/cloudvision.py", line 267, in load
    self.load_devices()
  File "/source/nautobot_ssot/integrations/aristacv/diffsync/adapters/cloudvision.py", line 72, in load_devices
    for index, dev in enumerate(cloudvision.get_devices(client=self.conn.comm_channel, import_active=True), start=1):
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/source/nautobot_ssot/integrations/aristacv/utils/cloudvision.py", line 270, in get_devices
    for resp in responses:
  File "/usr/local/lib/python3.11/site-packages/grpc/_channel.py", line 543, in __next__
    return self._next()
           ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/grpc/_channel.py", line 969, in _next
    raise self
grpc.RpcError
```

This was an error brought to me by @chambersh1129 while at Cisco Live. I need dig into it more but I wanted to get the issue open.  @chambersh1129 can you provide the python version you are using?

**Comment by chambersh1129** [comment]
Python Version: 3.11.9

PLUGINS_CONFIG Arista SSoT Snippet:
``` python
PLUGINS_CONFIG = {
    "nautobot_ssot": {
        "enable_aristacv": True,
        "aristacv_cvp_token": os.getenv("NAUTOBOT_ARISTACV_TOKEN", ""),
        "aristacv_cvaas_url": "www.arista.io:443",
        "aristacv_verify": is_truthy(os.getenv("NAUTOBOT_ARISTACV_VERIFY", True)),
        "aristacv_from_cloudvision_default_site": "cloudvision_imported",
        "aristacv_from_cloudvision_default_device_role": "network",
        "aristacv_from_cloudvision_default_device_role_color": "ff0000",
        "aristacv_delete_devices_on_sync": is_truthy(os.getenv("NAUTOBOT_ARISTACV_DELETE_ON_SYNC", False)),
        "aristacv_apply_import_tag": is_truthy(os.getenv("NAUTOBOT_ARISTACV_IMPORT_TAG", True)),
        "aristacv_import_active": is_truthy(os.getenv("NAUTOBOT_ARISTACV_IMPORT_ACTIVE", False)),
        "aristacv_create_controller": is_truthy(os.getenv("NAUTOBOT_ARISTACV_CREATE_CONTROLLER", False)),
        "aristacv_controller_site": os.getenv("NAUTOBOT_ARISTACV_CONTROLLER_SITE", ""),
        "aristacv_hostname_patterns": [],  # scrubbed
        "aristacv_site_mappings": {},  # scrubbed
        "aristacv_role_mappings": {},  # scrubbed
    },
}
```

**Comment by chambersh1129** [comment]
Following up on this, today I upgraded Nautobot and SSOT plugin:

- Nautobot: 2.2.4
- SSOT: 2.7.0
- Python: 3.11.9

I am getting the same exception.  Traceback:

```
[2024-08-14 19:05:19,967: INFO/ForkPoolWorker-7] nautobot.extras.jobs.run_job[d67d9ada-d4d5-4aa2-90ba-db54620e94ca]: Running job
[2024-08-14 19:05:20,014: INFO/ForkPoolWorker-7] nautobot.extras.jobs.run_job[d67d9ada-d4d5-4aa2-90ba-db54620e94ca]: Loading current data from source adapter...
[2024-08-14 19:05:20,054: INFO/ForkPoolWorker-7] nautobot.extras.jobs.run_job[d67d9ada-d4d5-4aa2-90ba-db54620e94ca]: Loading data from CloudVision
[2024-08-14 19:05:34,209: WARNING/ForkPoolWorker-7] Exception ignored in: 
[2024-08-14 19:05:34,217: WARNING/ForkPoolWorker-7] <function _Rendezvous.__del__ at 0x7fb798681440>
[2024-08-14 19:05:34,228: WARNING/ForkPoolWorker-7] Traceback (most recent call last):
[2024-08-14 19:05:34,231: WARNING/ForkPoolWorker-7]   File "/opt/nautobot/.local/lib/python3.11/site-packages/grpc/_channel.py", line 561, in __del__
[2024-08-14 19:05:34,235: WARNING/ForkPoolWorker-7]     
[2024-08-14 19:05:34,242: WARNING/ForkPoolWorker-7] with self._state.condition:
[2024-08-14 19:05:34,245: WARNING/ForkPoolWorker-7]  
[2024-08-14 19:05:34,254: WARNING/ForkPoolWorker-7]  
[2024-08-14 19:05:34,264: WARNING/ForkPoolWorker-7]  
[2024-08-14 19:05:34,270: WARNING/ForkPoolWorker-7]  
[2024-08-14 19:05:34,279: WARNING/ForkPoolWorker-7]  
[2024-08-14 19:05:34,283: WARNING/ForkPoolWorker-7]  
[2024-08-14 19:05:34,288: WARNING/ForkPoolWorker-7]  
[2024-08-14 19:05:34,292: WARNING/ForkPoolWorker-7]  
[2024-08-14 19:05:34,300: WARNING/ForkPoolWorker-7]  
[2024-08-14 19:05:34,307: WARNING/ForkPoolWorker-7] ^
[2024-08-14 19:05:34,318: WARNING/ForkPoolWorker-7] ^
[2024-08-14 19:05:34,333: WARNING/ForkPoolWorker-7] ^
[2024-08-14 19:05:34,338: WARNING/ForkPoolWorker-7] ^
[2024-08-14 19:05:34,344: WARNING/ForkPoolWorker-7] ^
[2024-08-14 19:05:34,348: WARNING/ForkPoolWorker-7] ^
[2024-08-14 19:05:34,353: WARNING/ForkPoolWorker-7] ^
[2024-08-14 19:05:34,357: WARNING/ForkPoolWorker-7] ^
[2024-08-14 19:05:34,365: WARNING/ForkPoolWorker-7] ^
[2024-08-14 19:05:34,370: WARNING/ForkPoolWorker-7] ^
[2024-08-14 19:05:34,377: WARNING/ForkPoolWorker-7] ^
[2024-08-14 19:05:34,380: WARNING/ForkPoolWorker-7] AttributeError
[2024-08-14 19:05:34,383: WARNING/ForkPoolWorker-7] : 
[2024-08-14 19:05:34,386: WARNING/ForkPoolWorker-7] '_MultiThreadedRendezvous' object has no attribute '_state'
[2024-08-14 19:05:34,389: WARNING/ForkPoolWorker-7] Exception ignored in: 
[2024-08-14 19:05:34,393: WARNING/ForkPoolWorker-7] <function _Rendezvous.__del__ at 0x7fb798681440>
[2024-08-14 19:05:34,396: WARNING/ForkPoolWorker-7] Traceback (most recent call last):
[2024-08-14 19:05:34,401: WARNING/ForkPoolWorker-7]   File "/opt/nautobot/.local/lib/python3.11/site-packages/grpc/_channel.py", line 561, in __del__
[2024-08-14 19:05:34,404: WARNING/ForkPoolWorker-7]     
[2024-08-14 19:05:34,409: WARNING/ForkPoolWorker-7] with self._state.condition:
[2024-08-14 19:05:34,412: WARNING/ForkPoolWorker-7]  
[2024-08-14 19:05:34,416: WARNING/ForkPoolWorker-7]  
[2024-08-14 19:05:34,421: WARNING/ForkPoolWorker-7]  
[2024-08-14 19:05:34,425: WARNING/ForkPoolWorker-7]  
[2024-08-14 19:05:34,429: WARNING/ForkPoolWorker-7]  
[2024-08-14 19:05:34,432: WARNING/ForkPoolWorker-7]  
[2024-08-14 19:05:34,434: WARNING/ForkPoolWorker-7]  
[2024-08-14 19:05:34,438: WARNING/ForkPoolWorker-7]  
[2024-08-14 19:05:34,442: WARNING/ForkPoolWorker-7]  
[2024-08-14 19:05:34,445: WARNING/ForkPoolWorker-7] ^
[2024-08-14 19:05:34,450: WARNING/ForkPoolWorker-7] ^
[2024-08-14 19:05:34,456: WARNING/ForkPoolWorker-7] ^
[2024-08-14 19:05:34,459: WARNING/ForkPoolWorker-7] ^
[2024-08-14 19:05:34,462: WARNING/ForkPoolWorker-7] ^
[2024-08-14 19:05:34,465: WARNING/ForkPoolWorker-7] ^
[2024-08-14 19:05:34,468: WARNING/ForkPoolWorker-7] ^
[2024-08-14 19:05:34,471: WARNING/ForkPoolWorker-7] ^
[2024-08-14 19:05:34,475: WARNING/ForkPoolWorker-7] ^
[2024-08-14 19:05:34,485: WARNING/ForkPoolWorker-7] ^
[2024-08-14 19:05:34,489: WARNING/ForkPoolWorker-7] ^
[2024-08-14 19:05:34,493: WARNING/ForkPoolWorker-7] AttributeError
[2024-08-14 19:05:34,496: WARNING/ForkPoolWorker-7] : 
[2024-08-14 19:05:34,500: WARNING/ForkPoolWorker-7] '_Rendezvous' object has no attribute '_state'
[2024-08-14 19:05:34,513: ERROR/ForkPoolWorker-7] Task nautobot.extras.jobs.run_job[d67d9ada-d4d5-4aa2-90ba-db54620e94ca] raised unexpected: RpcError()
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/celery/app/trace.py", line 477, in trace_task
    R = retval = fun(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/celery/app/trace.py", line 760, in __protected_call__
    return self.run(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/nautobot/extras/jobs.py", line 1136, in run_job
    result = job(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/nautobot/extras/jobs.py", line 149, in __call__
    return self.run(*args, **deserialized_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/nautobot/.local/lib/python3.11/site-packages/nautobot_ssot/integrations/aristacv/jobs.py", line 140, in run
    super().run(dryrun=self.dryrun, memory_profiling=self.memory_profiling, *args, **kwargs)
  File "/opt/nautobot/.local/lib/python3.11/site-packages/nautobot_ssot/jobs/base.py", line 317, in run
    self.sync_data(memory_profiling)
  File "/opt/nautobot/.local/lib/python3.11/site-packages/nautobot_ssot/jobs/base.py", line 136, in sync_data
    self.load_source_adapter()
  File "/opt/nautobot/.local/lib/python3.11/site-packages/nautobot_ssot/integrations/aristacv/jobs.py", line 119, in load_source_adapter
    self.source_adapter.load()
  File "/opt/nautobot/.local/lib/python3.11/site-packages/nautobot_ssot/integrations/aristacv/diffsync/adapters/cloudvision.py", line 269, in load
    self.load_devices()
  File "/opt/nautobot/.local/lib/python3.11/site-packages/nautobot_ssot/integrations/aristacv/diffsync/adapters/cloudvision.py", line 95, in load_devices
    self.load_device_tags(device=new_device)
  File "/opt/nautobot/.local/lib/python3.11/site-packages/nautobot_ssot/integrations/aristacv/diffsync/adapters/cloudvision.py", line 234, in load_device_tags
    system_tags = cloudvision.get_tags_by_type(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/nautobot/.local/lib/python3.11/site-packages/nautobot_ssot/integrations/aristacv/utils/cloudvision.py", line 287, in get_tags_by_type
    for resp in responses:
  File "/opt/nautobot/.local/lib/python3.11/site-packages/grpc/_channel.py", line 543, in __next__
    return self._next()
           ^^^^^^^^^^^^
  File "/opt/nautobot/.local/lib/python3.11/site-packages/grpc/_channel.py", line 969, in _next
    raise self
grpc.RpcError
```

**Comment by jdrew82** [comment]
@chambersh1129 Is this still an issue? Unfortunately, we don't have a CVP instance to test against at this time so we can't validate if this is still occurring or how to fix it.

**Comment by jdrew82** [comment]
@chambersh1129 Can you see if the PR #580 solves the issue you're experiencing? It should at least allow the code to bypass the RpcError that's being thrown.

**Comment by chambersh1129** [comment]
Hi @jdrew82, we shifted course and started using the IPFabric integration which is working for us.  I currently don't have the cycles nor a DEV environment to test the Arista CV integration and the IPFabric integration is vendor agnostic and all inclusive.

This can be kept open if you want to use it for tracking/reminder to test in the future.  If I'm the only person who has brought up the issue then it can be closed/resolved.

**Comment by jdrew82** [comment]
@chambersh1129 Appreciate the response. The Arista team has reached out to provide a test instance for us to use. I believe they stated they were able to reproduce the issue so we should hopefully have a fix available in the near future. I'll leave this open for the time being while we work to resolve the bug.
