### ISSUE TITLE
DNAC Integration Not Working 

### ISSUE THREAD

**Issue by ShivaniMauryaIntel** [nautobot/nautobot-app-ssot#540]
### Environment
* Python version:  3.9.18
* Nautobot version:  2.3.2
* nautobot-ssot version:  3.1.0

### Expected Behavior
[DNA Center to Nautobot] job appears under Job section

### Observed Behavior
[DNA Center to Nautobot] job doesn't appears under Job section. 

### Steps to Reproduce
1. Upgrade nautobot to v2.3.2
2. Upgrade nautobot-ssot to v3.1.0
3. Integrate DNA center plugin by following the document - https://docs.nautobot.com/projects/ssot/en/latest/admin/integrations/dna_center_setup/
4. Go to Nautobot GUI -> Installed Apps -> SSOT 
5. Under Jobs section, you can see both ACI & DNA Center Job -
![image](https://github.com/user-attachments/assets/dacccd37-19cb-45ce-a4f1-d36046835464)

6. Click on DNA Center to Nautobot Job 
7. You will get this error message -
![image](https://github.com/user-attachments/assets/c9a70d6e-44d4-4a73-9b61-ce1fbc8f3b1b)

**Comment by jdrew82** [comment]
@ShivaniMauryaIntel Can you review the logs of your Nautobot process and confirm if you see the following?

```
nautobot-1  | 01:23:27.834 DEBUG   nautobot.core.celery __init__.py                      register_jobs() : Registering job nautobot_ssot.integrations.dna_center.jobs.DnaCenterDataSource
nautobot-1  | 01:23:27.835 DEBUG   nautobot.core.celery __init__.py                      register_jobs() : Registering job nautobot_ssot.integrations.aci.jobs.AciDataSource
```

If you have the integration installed correctly you should see that in the startup logs.

**Comment by jdrew82** [comment]
BTW, I've attempted to reproduce this and been unable to. I see the Jobs in the Jobs menu and the links from the Installed Apps page works. Perhaps there's a permissions issue or something else? Do you see anything else in the logs when you try to load the Jobs menu or click on the links from Installed Apps?

**Comment by ShivaniMauryaIntel** [comment]
This is what I can see in the logs - 
![image](https://github.com/user-attachments/assets/8db8c369-02df-453b-b21d-1894db482773)

I have installed DNAC plugin using below command - 
pip install nautobot-ssot[dna_center]

This is how my nautobot_config.py file looks -
![image](https://github.com/user-attachments/assets/d8a4ffd1-0c8f-49b5-9de6-0ef73e94ad8f)

**Comment by ShivaniMauryaIntel** [comment]
Issue resolved now. I ran this command - nautobot-server post_upgrade

**Comment by jdrew82** [comment]
@ShivaniMauryaIntel Can you re-run the Job with Debug enabled? That should show a log right before the error that contains the information attempting to be processed. It appears that one of the IP Addresses that's on the

**Comment by ShivaniMauryaIntel** [comment]
Hi @jdrew82  I searched for "error" level log message, but it is not present in the log output. I can only find warning & info logs. 
Below is the output with debug enabled -

Traceback (most recent call last):
  File "/opt/nautobot/lib64/python3.9/site-packages/nautobot_ssot/integrations/dna_center/diffsync/adapters/dna_center.py", line 321, in load_devices
    device_found = self.get(self.device, dev["hostname"])
  File "/opt/nautobot/lib64/python3.9/site-packages/diffsync/__init__.py", line 724, in get
    return self.store.get(model=obj, identifier=identifier)
  File "/opt/nautobot/lib64/python3.9/site-packages/diffsync/store/local.py", line 49, in get
    raise ObjectNotFound(f"{modelname} {uid} not present in {str(self)}")
diffsync.exceptions.ObjectNotFound: device WLANi-cont13 not present in LocalStore

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/nautobot/lib64/python3.9/site-packages/nautobot_ssot/integrations/dna_center/diffsync/adapters/dna_center.py", line 372, in load_ports
    found_port = self.get(
  File "/opt/nautobot/lib64/python3.9/site-packages/diffsync/__init__.py", line 724, in get
    return self.store.get(model=obj, identifier=identifier)
  File "/opt/nautobot/lib64/python3.9/site-packages/diffsync/store/local.py", line 49, in get
    raise ObjectNotFound(f"{modelname} {uid} not present in {str(self)}")
diffsync.exceptions.ObjectNotFound: port redundancy-port__WLANi-cont13 not present in LocalStore

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/nautobot/lib64/python3.9/site-packages/celery/app/trace.py", line 477, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/opt/nautobot/lib64/python3.9/site-packages/celery/app/trace.py", line 760, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/nautobot/lib64/python3.9/site-packages/nautobot/extras/jobs.py", line 1136, in run_job
    result = job(*args, **kwargs)
  File "/opt/nautobot/lib64/python3.9/site-packages/nautobot/extras/jobs.py", line 149, in __call__
    return self.run(*args, **deserialized_kwargs)
  File "/opt/nautobot/lib64/python3.9/site-packages/nautobot_ssot/integrations/dna_center/jobs.py", line 120, in run
    super().run(dryrun=self.dryrun, memory_profiling=self.memory_profiling, *args, **kwargs)
  File "/opt/nautobot/lib64/python3.9/site-packages/nautobot_ssot/jobs/base.py", line 330, in run
    self.sync_data(memory_profiling)
  File "/opt/nautobot/lib64/python3.9/site-packages/nautobot_ssot/jobs/base.py", line 149, in sync_data
    self.load_source_adapter()
  File "/opt/nautobot/lib64/python3.9/site-packages/nautobot_ssot/integrations/dna_center/jobs.py", line 95, in load_source_adapter
    self.source_adapter.load()
  File "/opt/nautobot/lib64/python3.9/site-packages/nautobot_ssot/integrations/dna_center/diffsync/adapters/dna_center.py", line 496, in load
    self.load_devices()
  File "/opt/nautobot/lib64/python3.9/site-packages/nautobot_ssot/integrations/dna_center/diffsync/adapters/dna_center.py", line 351, in load_devices
    self.load_ports(device_id=dev["id"], dev=new_dev, mgmt_addr=dev["managementIpAddress"])
  File "/opt/nautobot/lib64/python3.9/site-packages/nautobot_ssot/integrations/dna_center/diffsync/adapters/dna_center.py", line 409, in load_ports
    mask_length = netmask_to_cidr(addr["address"]["ipMask"]["address"])
  File "/opt/nautobot/lib64/python3.9/site-packages/netutils/ip.py", line 410, in netmask_to_cidr
    raise ValueError("Subnet mask is not valid.")
ValueError: Subnet mask is not valid.

**Comment by jdrew82** [comment]
@ShivaniMauryaIntel That sounds like a configuration issue on the device or in DNA Center. I'm a bit confused as to how a Device doesn't have a netmask configured. Can you clarify if these Devices truly have just a host IP Address without a netmask configured on the Interface? Are these all /32 so perhaps it's just a default if undefined? I'm trying to understand how we should be handling this as we never saw this issue with the client I created the integration for.

**Comment by jdrew82** [comment]
I'm going to close this out as we haven't heard anything back in months and this integration is confirmed working. This issue sounded like a configuration issue on a Device that is outside the purview of this integration.
