### ISSUE TITLE
Pydantic validation error for CloudvisionCustomField when syncing data

### ISSUE THREAD

**Issue by erjac77** [nautobot/nautobot-app-ssot#609]
### Environment
* Python version:  3.11.10
* Nautobot version:  2.3.12
* nautobot-ssot version:  3.2.0

### Expected Behavior

Sync from CV to Nautobot should finish successfully.

### Observed Behavior

When syncing data from CloudVision to Nautobot, we get the following error:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/celery/app/trace.py", line 477, in trace_task
    R = retval = fun(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/nautobot/extras/jobs.py", line 1136, in run_job
    result = job(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/nautobot/extras/jobs.py", line 149, in __call__
    return self.run(*args, **deserialized_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/nautobot_ssot/integrations/aristacv/jobs.py", line 125, in run
    super().run(dryrun=self.dryrun, memory_profiling=self.memory_profiling, *args, **kwargs)
  File "/usr/local/lib/python3.11/site-packages/nautobot_ssot/jobs/base.py", line 355, in run
    self.sync_data(memory_profiling)
  File "/usr/local/lib/python3.11/site-packages/nautobot_ssot/jobs/base.py", line 158, in sync_data
    self.load_source_adapter()
  File "/usr/local/lib/python3.11/site-packages/nautobot_ssot/integrations/aristacv/jobs.py", line 104, in load_source_adapter
    self.source_adapter.load()
  File "/usr/local/lib/python3.11/site-packages/nautobot_ssot/integrations/aristacv/diffsync/adapters/cloudvision.py", line 303, in load
    self.load_devices()
  File "/usr/local/lib/python3.11/site-packages/nautobot_ssot/integrations/aristacv/diffsync/adapters/cloudvision.py", line 105, in load_devices
    self.load_device_tags(device=new_device)
  File "/usr/local/lib/python3.11/site-packages/nautobot_ssot/integrations/aristacv/diffsync/adapters/cloudvision.py", line 289, in load_device_tags
    new_cf = [self.cf](http://self.cf/)(
             ^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pydantic/main.py", line 214, in __init__
    validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pydantic_core._pydantic_core.ValidationError: 1 validation error for CloudvisionCustomField
value
  Input should be a valid string [type=string_type, input_value=True, input_type=bool]
    For further information visit https://errors.pydantic.dev/2.10/v/string_type
```

Some CloudvisionCustomField are defined as `int` or `bool`, but the DiffSync model expects a `str`. 

`{'name': 'arista_vxlanConfigured', 'value': True, 'device_name': 'MYSWITCH'}`

https://github.com/nautobot/nautobot-app-ssot/blob/2ea8bd3f4818a3904c287c69736fce036de214be/nautobot_ssot/integrations/aristacv/signals.py#L107

https://github.com/nautobot/nautobot-app-ssot/blob/2ea8bd3f4818a3904c287c69736fce036de214be/nautobot_ssot/integrations/aristacv/diffsync/models/base.py#L135

### Steps to Reproduce

1. Go to SSoT Dashboard page
2. Launch a sync job (CloudVision -> Nautobot)

**Comment by ksoufan** [comment]
I got similar error for Pydantic, but with different output

  File "/opt/nautobot/lib/python3.10/site-packages/pydantic/main.py", line 214, in __init__
    validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
pydantic_core._pydantic_core.ValidationError: 1 validation error for CloudvisionCustomField
value
  Input should be a valid string [type=string_type, input_value=False, input_type=bool]
    For further information visit https://errors.pydantic.dev/2.10/v/string_type

**Comment by noredistribution** [comment]
I've hit this as well and had to make a few changes

1) https://github.com/nautobot/nautobot-app-ssot/blob/87e21a4e699711ecf91b8743276af7ef42f96088/nautobot_ssot/integrations/aristacv/diffsync/models/base.py#L135

from:
 
`value: str`

to:

`value: Union[str, int, bool]`

This requires `from typing import Union` on the top

then I was hitting other validation errors

```
[2025-05-09 00:07:54,502: ERROR/ForkPoolWorker-6] Task nautobot.extras.jobs.run_job[be26aa8e-4558-4da7-a9c4-914044510be0] raised unexpected: 1 validation error for NautobotCustomField
value
  Input should be a valid string [type=string_type, input_value=True, input_type=bool]
    For further information visit https://errors.pydantic.dev/2.11/v/string_type
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/celery/app/trace.py", line 477, in trace_task
    R = retval = fun(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/celery/app/trace.py", line 760, in __protected_call__
    return self.run(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/nautobot/extras/jobs.py", line 1136, in run_job
    result = job(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/nautobot/extras/jobs.py", line 149, in __call__
    return self.run(*args, **deserialized_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/source/nautobot_ssot/integrations/aristacv/jobs.py", line 125, in run
    super().run(dryrun=self.dryrun, memory_profiling=self.memory_profiling, *args, **kwargs)
  File "/source/nautobot_ssot/jobs/base.py", line 358, in run
    self.sync_data(memory_profiling)
  File "/source/nautobot_ssot/jobs/base.py", line 172, in sync_data
    self.load_target_adapter()
  File "/source/nautobot_ssot/integrations/aristacv/jobs.py", line 110, in load_target_adapter
    self.target_adapter.load()
  File "/source/nautobot_ssot/integrations/aristacv/diffsync/adapters/nautobot.py", line 200, in load
    self.load_devices()
  File "/source/nautobot_ssot/integrations/aristacv/diffsync/adapters/nautobot.py", line 65, in load_devices
    self.load_custom_fields(dev=dev)
  File "/source/nautobot_ssot/integrations/aristacv/diffsync/adapters/nautobot.py", line 72, in load_custom_fields
    new_cf = self.cf(
             ^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pydantic/main.py", line 253, in __init__
    validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pydantic_core._pydantic_core.ValidationError: 1 validation error for NautobotCustomField
value
  Input should be a valid string [type=string_type, input_value=True, input_type=bool]
    For further information visit https://errors.pydantic.dev/2.11/v/string_type
```

for that I changed https://github.com/nautobot/nautobot-app-ssot/blob/87e21a4e699711ecf91b8743276af7ef42f96088/nautobot_ssot/integrations/aristacv/diffsync/adapters/nautobot.py#L67-L80

from:

```python
    def load_custom_fields(self, dev: OrmDevice):
        """Load device custom field data from Nautobot and populate DiffSync models."""
        for cf_name, cf_value in dev.custom_field_data.items():
            if cf_name.startswith("arista_"):
                try:
                    new_cf = self.cf(
                        name=cf_name,
                        value=cf_value if cf_value is not None else "",
                        device_name=dev.name,
                    )
                    self.add(new_cf)
                except AttributeError as err:
                    self.job.logger.warning(f"Unable to load {cf_name}. {err}")
                    continue
```

to:

```python
    def load_custom_fields(self, dev: OrmDevice):
        """Load device custom field data from Nautobot and populate DiffSync models."""
        print(dev.custom_field_data.items())
        for cf_name, cf_value in dev.custom_field_data.items():
            if cf_name.startswith("arista_"):
                try:
                    # Convert boolean values to strings
                    if isinstance(cf_value, bool):
                        cf_value = str(cf_value)

                    new_cf = self.cf(
                        name=cf_name,
                        value=cf_value if cf_value is not None else "",
                        device_name=dev.name,
                    )
                    self.add(new_cf)
                except AttributeError as err:
                    self.job.logger.warning(f"Unable to load {cf_name}. {err}")
                    continue
```

basically stringifying the value if it's a boolean

and then I've hit another issues in the model too with this traceback:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/celery/app/trace.py", line 477, in trace_task
    R = retval = fun(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/celery/app/trace.py", line 760, in __protected_call__
    return self.run(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/nautobot/extras/jobs.py", line 1136, in run_job
    result = job(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/nautobot/extras/jobs.py", line 149, in **call**
    return self.run(*args, **deserialized_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/source/nautobot_ssot/integrations/aristacv/jobs.py", line 125, in run
    super().run(dryrun=self.dryrun, memory_profiling=self.memory_profiling, *args, **kwargs)
  File "/source/nautobot_ssot/jobs/base.py", line 358, in run
    self.sync_data(memory_profiling)
  File "/source/nautobot_ssot/jobs/base.py", line 200, in sync_data
    self.execute_sync()
  File "/source/nautobot_ssot/jobs/base.py", line 99, in execute_sync
    self.source_adapter.sync_to(self.target_adapter, flags=self.diffsync_flags)
  File "/usr/local/lib/python3.11/site-packages/diffsync/__init__.py", line 627, in sync_to
    return target.sync_from(self, diff_class=diff_class, flags=flags, callback=callback, diff=diff)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/diffsync/__init__.py", line 599, in sync_from
    result = syncer.perform_sync()
             ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/diffsync/helpers.py", line 331, in perform_sync
    changed |= self.sync_diff_element(element)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/diffsync/helpers.py", line 381, in sync_diff_element
    changed, modified_model = self.sync_model(src_model=src_model, dst_model=dst_model, ids=ids, attrs=attrs)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/diffsync/helpers.py", line 430, in sync_model
    dst_model = self.model_class.create(adapter=self.dst_diffsync, ids=ids, attrs=attrs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/source/nautobot_ssot/integrations/aristacv/diffsync/models/nautobot.py", line 382, in create
    return super().create(ids=ids, adapter=adapter, attrs=attrs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/diffsync/__init__.py", line 242, in create
    return cls.create_base(adapter=adapter, ids=ids, attrs=attrs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/diffsync/__init__.py", line 219, in create_base
    model = cls(**ids, adapter=adapter, **attrs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pydantic/main.py", line 253, in **init**     validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ pydantic_core._pydantic_core.ValidationError: 1 validation error for NautobotCustomField value   Input should be a valid string [type=string_type, input_value=True, input_type=bool]     For further information visit https://errors.pydantic.dev/2.11/v/string_type
```

and for that I edited https://github.com/nautobot/nautobot-app-ssot/blob/87e21a4e699711ecf91b8743276af7ef42f96088/nautobot_ssot/integrations/aristacv/diffsync/models/nautobot.py#L364-L382

from:

```python
class NautobotCustomField(CustomField):
    """Nautobot CustomField model."""

    @classmethod
    def create(cls, adapter, ids, attrs):
        """Create Custom Field in Nautobot."""
        try:
            attrs["value"] = bool(distutils.util.strtobool(attrs["value"]))
        except ValueError:
            # value isn't convertable to bool so continue
            pass
        device = OrmDevice.objects.get(name=ids["device_name"])
        try:
            device.custom_field_data.update({ids["name"]: attrs["value"]})
            device.validated_save()
        except ValidationError:
            if ids["name"] not in MISSING_CUSTOM_FIELDS:
                adapter.job.logger.warning(
                    f"Custom field {ids['name']} is not defined. You can create the custom field in the Admin UI."
                )
            MISSING_CUSTOM_FIELDS.append(ids["name"])

        return super().create(ids=ids, adapter=adapter, attrs=attrs)

    def update(self, attrs):
        """Update Custom Field in Nautobot."""
        try:
            attrs["value"] = bool(distutils.util.strtobool(attrs["value"]))
        except ValueError:
            # value isn't convertable to bool so continue
            pass
        device = OrmDevice.objects.get(name=self.device_name)
        device.custom_field_data.update({self.name: attrs["value"]})
        device.validated_save()
        return super().update(attrs)

    def delete(self):
        """Delete Custom Field in Nautobot."""
        try:
            device = OrmDevice.objects.get(name=self.device_name)
            device.custom_field_data.update({self.name: None})
            device.validated_save()
            super().delete()
            return self
        except OrmDevice.DoesNotExist:
            # Do not need to delete customfield if the device does not exist.
            return self
```

to

```python
class NautobotCustomField(CustomField):
    """Nautobot CustomField model."""

    @classmethod
    def create(cls, adapter, ids, attrs):
        """Create Custom Field in Nautobot."""
        # Original code tries to convert strings to boolean
        # We need to ensure the value is a string for the model validation
        try:
            # Check if we're dealing with a string first
            if isinstance(attrs["value"], str):
                try:
                    # If it's a string representation of a boolean, convert it to actual boolean
                    attrs["value"] = bool(distutils.util.strtobool(attrs["value"]))
                except ValueError:
                    # value isn't convertable to bool so continue
                    pass
            # Then ensure the final value that gets passed to the parent class is a string
            if isinstance(attrs["value"], bool):
                # Save the boolean for Nautobot but convert to string for the model
                nautobot_value = attrs["value"]
                model_value = str(attrs["value"])
            else:
                nautobot_value = attrs["value"]
                model_value = attrs["value"]

            device = OrmDevice.objects.get(name=ids["device_name"])
            try:
                device.custom_field_data.update({ids["name"]: nautobot_value})
                device.validated_save()
            except ValidationError:
                if ids["name"] not in MISSING_CUSTOM_FIELDS:
                    adapter.job.logger.warning(
                        f"Custom field {ids['name']} is not defined. You can create the custom field in the Admin UI."
                    )
                MISSING_CUSTOM_FIELDS.append(ids["name"])

            # Use the string value for the model
            attrs_for_model = attrs.copy()
            attrs_for_model["value"] = model_value

            return super().create(ids=ids, adapter=adapter, attrs=attrs_for_model)
        except KeyError:
            # If "value" is not in attrs, just pass through
            return super().create(ids=ids, adapter=adapter, attrs=attrs)

    def update(self, attrs):
        """Update Custom Field in Nautobot."""
        try:
            # Similar logic to create
            if isinstance(attrs["value"], str):
                try:
                    attrs["value"] = bool(distutils.util.strtobool(attrs["value"]))
                except ValueError:
                    # value isn't convertable to bool so continue
                    pass

            # Save the original value for Nautobot
            nautobot_value = attrs["value"]

            # Convert bool to string if needed for the model update
            if isinstance(attrs["value"], bool):
                attrs_for_model = attrs.copy()
                attrs_for_model["value"] = str(attrs["value"])
            else:
                attrs_for_model = attrs

            device = OrmDevice.objects.get(name=self.device_name)
            device.custom_field_data.update({self.name: nautobot_value})
            device.validated_save()

            return super().update(attrs_for_model)
        except KeyError:
            # If "value" is not in attrs, just pass through
            return super().update(attrs)

    def delete(self):
        """Delete Custom Field in Nautobot."""
        try:
            device = OrmDevice.objects.get(name=self.device_name)
            device.custom_field_data.update({self.name: None})
            device.validated_save()
            super().delete()
            return self
        except OrmDevice.DoesNotExist:
            # Do not need to delete customfield if the device does not exist.
            return self
```

Note that I don't fully understand why some of these types are forced and conflicting in some of the code, but the above changes helped me sync CV to Nautobot.
